#%RAML 1.0 Trait
securedBy:
queryParameters:
    clientId:
      displayName: Client ID
      description: Fallback Query Parameter to use if x-client-id header cannot be set.
      type: string
      example: "a123456"
      required: true
    clientSecret:
      displayName: Client Secret
      description: Fallback Query Parameter to use if x-client-secret header cannot be set.
      type: string
      example: "a123456"
      required: true
  