#%RAML 1.0 DataType
type: object
properties:
  First Name: 
    type: string
    maxLength: 20
    minLength: 5
  Last Name:
    type: string
    maxLength: 20
    minLength: 5
  contact No:
    type: number
  email:
    type: string
  Pan card:
    type: string
  address:
    type: !include address.raml
  benificiary Details:
    type: !include beneficiary-details.raml

      
